### ISSUE TITLE
Data Preprocessing

### ISSUE THREAD

**Issue by Asifdotexe** [Asifdotexe/MachineUnderstandsTextData#1]
## Data Processing or Text Processing
In this issue we will be talking about different approaches for pre-processing and cleaning textual data in Natural Language Processing

### Task List
- [x] Changing to lowercase
- [x] Removing URLs
- [x] Removing remove non-word and non-whitespace characters
- [x] Removing digits
- [x] Tokenization
- [x] Stop-word removal
- [x] Stemming
- [x] Lemmatization
